"""add is_active to api_groups

Revision ID: 024a93172069
Revises: 7d106a331687
Create Date: 2026-04-02 21:03:03.270449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024a93172069'
down_revision: Union[str, Sequence[str], None] = '7d106a331687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_groups', sa.Column('is_active', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_groups', 'is_active')
    # ### end Alembic commands ###
