"""add archived to analyses and reports

Revision ID: 24b18b5aa918
Revises: 024a93172069
Create Date: 2026-04-06 13:28:47.624246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b18b5aa918'
down_revision: Union[str, Sequence[str], None] = '024a93172069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('archived', sa.Boolean(), server_default=sa.text("'FALSE'"), nullable=False))
    op.add_column('reports', sa.Column('archived', sa.Boolean(), server_default=sa.text("'FALSE'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'archived')
    op.drop_column('analyses', 'archived')
    # ### end Alembic commands ###
