"""add playbook_templates subject_sources subject_source_runs

Revision ID: 4678d7bafb70
Revises: a0f92401cd79
Create Date: 2026-04-01 10:34:27.295990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4678d7bafb70'
down_revision: Union[str, Sequence[str], None] = 'a0f92401cd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbook_templates',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_type', postgresql.ENUM('company', 'product', 'service', 'topic', name='gsubject_type_enum', create_type=False), nullable=False),
    sa.Column('category_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('category_group', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('default_frequency_minutes', sa.Integer(), server_default=sa.text('360'), nullable=False),
    sa.Column('collection_tool', sa.VARCHAR(length=32), nullable=False),
    sa.Column('collection_config', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('signal_instructions', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('user_inputs_schema', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('subject_type', 'category_key', name='uq_playbook_subject_type_category')
    )
    op.create_table('subject_sources',
    sa.Column('source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gsubject_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('category_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), server_default=sa.text('360'), nullable=False),
    sa.Column('collection_tool', sa.VARCHAR(length=32), nullable=False),
    sa.Column('collection_config', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('signal_instructions', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('user_inputs', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.VARCHAR(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('last_status_text', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gsubject_id'], ['group_subjects.gsubject_id'], name='fk_subject_sources_gsubject_id'),
    sa.ForeignKeyConstraint(['template_id'], ['playbook_templates.template_id'], name='fk_subject_sources_template_id'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_subject_sources_deleted'), 'subject_sources', ['deleted'], unique=False)
    op.create_index('ix_subject_sources_gsubject_deleted', 'subject_sources', ['gsubject_id', 'deleted'], unique=False)
    op.create_table('subject_source_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('items_collected', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('data_hash', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['subject_sources.source_id'], name='fk_source_runs_source_id'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_source_runs_source_started', 'subject_source_runs', ['source_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_runs_source_started', table_name='subject_source_runs')
    op.drop_table('subject_source_runs')
    op.drop_index('ix_subject_sources_gsubject_deleted', table_name='subject_sources')
    op.drop_index(op.f('ix_subject_sources_deleted'), table_name='subject_sources')
    op.drop_table('subject_sources')
    op.drop_table('playbook_templates')
    # ### end Alembic commands ###
