"""add conversations and messages tables

Revision ID: 572b732de5e6
Revises: a1b17d342a6f
Create Date: 2026-04-01 22:57:54.853502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572b732de5e6'
down_revision: Union[str, Sequence[str], None] = 'a1b17d342a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gsubject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gsubject_id'], ['group_subjects.gsubject_id'], name='fk_conversations_gsubject_id'),
    sa.ForeignKeyConstraint(['user_id'], ['api_users.user_id'], name='fk_conversations_user_id'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('ix_conversations_gsubject_created', 'conversations', ['gsubject_id', 'created_at'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=16), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=32), server_default=sa.text("'text'"), nullable=False),
    sa.Column('metadata_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'ok'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], name='fk_messages_conversation_id'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_messages_conversation_created', 'conversation_messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_created', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_conversations_gsubject_created', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
