"""initial schema v2

Revision ID: a0f92401cd79
Revises: 
Create Date: 2026-04-01 00:05:01.971929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'a0f92401cd79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_groups',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('group_name', sa.VARCHAR(), server_default=sa.text("'Undefined group'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_api_groups_deleted'), 'api_groups', ['deleted'], unique=False)
    op.create_table('api_settings',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('api_users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('group_id', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_groupadmin', sa.Boolean(), server_default=sa.text("'FALSE'"), nullable=False),
    sa.Column('is_subjectmanager', sa.Boolean(), server_default=sa.text("'FALSE'"), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.CheckConstraint("char_length(user_name) BETWEEN 3 AND 32 AND user_name ~ '^[a-z0-9_-]+$'", name='ck_api_users_user_name_format'),
    sa.ForeignKeyConstraint(['group_id'], ['api_groups.group_id'], name='fk_api_users_group_id'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_name', name='uq_api_users_user_name')
    )
    op.create_index(op.f('ix_api_users_deleted'), 'api_users', ['deleted'], unique=False)
    op.create_index(op.f('ix_api_users_email'), 'api_users', ['email'], unique=True)
    op.create_table('group_settings',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['api_groups.group_id'], name='fk_group_settings_group_id'),
    sa.PrimaryKeyConstraint('group_id', 'name')
    )
    op.create_table('group_subjects',
    sa.Column('gsubject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('gsubject_seqn', sa.Integer(), nullable=False),
    sa.Column('gsubject_type', sa.Enum('company', 'product', 'service', 'topic', name='gsubject_type_enum'), nullable=False),
    sa.Column('gsubject_name', sa.VARCHAR(), server_default=sa.text("'No subject name'"), nullable=False),
    sa.Column('gsubject_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gsubject_status', sa.VARCHAR(), server_default=sa.text("'warning'"), nullable=False),
    sa.Column('gsubject_status_text', sa.VARCHAR(), server_default=sa.text("''"), nullable=False),
    sa.Column('gsubject_status_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['api_groups.group_id'], name='fk_group_subjects_group_id'),
    sa.PrimaryKeyConstraint('gsubject_id')
    )
    op.create_index(op.f('ix_group_subjects_deleted'), 'group_subjects', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_subjects_deleted'), table_name='group_subjects')
    op.drop_table('group_subjects')
    op.drop_table('group_settings')
    op.drop_index(op.f('ix_api_users_email'), table_name='api_users')
    op.drop_index(op.f('ix_api_users_deleted'), table_name='api_users')
    op.drop_table('api_users')
    op.drop_table('api_settings')
    op.drop_index(op.f('ix_api_groups_deleted'), table_name='api_groups')
    op.drop_table('api_groups')
    # ### end Alembic commands ###
