"""add analyses and reports tables

Revision ID: a1b17d342a6f
Revises: 4678d7bafb70
Create Date: 2026-04-01 19:19:30.124146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b17d342a6f'
down_revision: Union[str, Sequence[str], None] = '4678d7bafb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('analysis_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gsubject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analysis_type', sa.VARCHAR(length=32), server_default=sa.text("'full'"), nullable=False),
    sa.Column('summary', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('key_findings', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('signals', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('raw_analysis', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sources_analyzed', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gsubject_id'], ['group_subjects.gsubject_id'], name='fk_analyses_gsubject_id'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index('ix_analyses_gsubject_created', 'analyses', ['gsubject_id', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('gsubject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=32), server_default=sa.text("'battlecard'"), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), server_default=sa.text("''"), nullable=False),
    sa.Column('content_markdown', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.analysis_id'], name='fk_reports_analysis_id'),
    sa.ForeignKeyConstraint(['gsubject_id'], ['group_subjects.gsubject_id'], name='fk_reports_gsubject_id'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('ix_reports_gsubject_created', 'reports', ['gsubject_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_gsubject_created', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_analyses_gsubject_created', table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
